### ISSUE TITLE
Unable to login with default admin credentials

### ISSUE THREAD

**Issue by Hezkore** [YunoHost-Apps/owncast_ynh#52]
### Describe the bug

I am unable to login with default admin credentials after the initial install.

This is the only install I've ever had of Owncast, and the only time I've accessed an Owncast instance.

Tested on Linux with FireFox and Vivialdi.
Tested on Windows with Edge, Vivaldi, Brave, Firefox, Mercury and Opera.

UPDATE:
Now also tested in Tor browser on a different internet connection.
Also tested on Android Chrome using 5G.

### Context

- Hardware: *VPS bought online*
- YunoHost version: *12.0.4.1 (testing)*
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: *0.1.3~ynh2*
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

1. Create a sub-domain
2. Install Owncast to sub-domain
3. Visit Owncast sub-domain /admin
4. At login, user: admin, pass: abc123
5. Login screen flashes, user is not logged in

### Expected behavior

A successful login with the provided credentials after install.

### Logs

Oct 20 23:43:42 owncast[3712016]: time="2024-10-20T23:43:42Z" level=info msg="Web server is listening on port 39050."
Oct 20 23:43:42 owncast[3712016]: time="2024-10-20T23:43:42Z" level=info msg="Configure this server by visiting /admin."
Oct 20 23:44:10 owncast[3712016]: time="2024-10-20T23:44:10Z" level=debug msg="Failed admin authentication"

**Comment by Hezkore** [comment]
This was closed without an explanation, so I'll go ahead and say that this is currently fixed in "testing".
`sudo yunohost app upgrade owncast -u https://github.com/YunoHost-Apps/owncast_ynh/tree/testing`

**Comment by Tagadda** [comment]
This issue was closed when #54 was merged to master.
You can upgrade your app as usual.

**Comment by monkee-ch** [comment]
Can confirm the Bug on fresh install. tried Yunohost GUI, CLI with testing and master branch

**Comment by TMTwatch** [comment]
On a fresh install from master the default credentials still don't work. I tried installing and removing 3 times.

**Comment by TMTwatch** [comment]
An update showed up today! I just installed it and now the default credentials work! Thanks for the speedy fix!

**Comment by steko** [comment]
I see this happening on a fresh install, on a VPS.
Version : 0.2.1~ynh1

**Comment by TMTwatch** [comment]
This should be reopened. It's still present on a fresh installation
